# Umbraco Bot Settings
# Aka automate the dull things & lend a hand to Seb :)

# Settings for the no label functionality
nolabels:
  
  # If this feature is enable or disabled
  enabled: false

  # The label must start with the following for the bot allow the issue to be closed
  releaseLabel: release/

  # What the bot will reply with when no labels are present
  missingRelease: Please add a release label @{{ username }}

  # What the bot will reply with when no labels are present
  missing: You are missing a label. Please add one to this issue before closing @{{ username }}
